version: '3.4'

services:
  api.gateway:
    hostname: gateway
    image: ${DOCKER_REGISTRY-}tysafeapigateway
    build:
      context: .
      dockerfile: TySafe.Api.Gateway/Dockerfile
    depends_on:
      - api.gateway.database

  api.gateway.database:
    hostname: db.dateway
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  # Development dependencies
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
        
  seq:
    hostname: seq
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - tysafe-seq:/data
    ports:
      - "5341:80"

volumes:
  tysafe-seq: